### ISSUE TITLE
[REFACTOR] 1.0 이후 개선 및 추가 사항

### ISSUE THREAD

**Issue by ahn-sj** [cround-team/cround-server#157]
## 기능 설명
Here!

## 기능 상세
- [ ] #15 , #143 
- [ ] #141 
- [x] HTTP 서버 통신 ((as-is)web flux -> (to-be)openfeign)
- [ ] 계정 통합 (page login, kakao login, google login)
- [ ] HTTP 1.1 -> HTTP 2.0
- [ ] 테이블 정규화 및 채팅 권한 추가

## TODO
- [ ] Here!

### 기타 논의 사항
- Here!
