### ISSUE TITLE
[FEAT] Bookmark, Like, ShortClass, Contents Entity를 생성한다.

### ISSUE THREAD

**Issue by ahn-sj** [cround-team/cround-server#23]
## 기능 설명
Bookmark, Like, ShortClass, Contents Entity를 생성한다.

## 기능 상세
- [x] 북마크 (Bookmark in Contents, ShortClass Entity)
- [x] 좋아요 (Like in Contents, ShortClass Entity)
- [x] #59
- [x] 콘텐츠 (Contents table)

## TODO
- [ ] 좋아요와 북마크 개수는 검색 결과(또는 메인페이지)에 개수를 보여지는 형태이다. (하단 샘플 단락 이미지를 참고)
- [x] 좋아요와 북마크의 상태는 [좋아요 개수 조회 최적화하기](https://tecoble.techcourse.co.kr/post/2022-10-10-like-count/)를 참고하여 적절한 방법으로 도입한다.
- [ ] 로그인이 된 사용자라면 본인이 좋아요, 북마크, 팔로우한 상태를 나타낸다.
- [ ] 숏클래스에 담을 동영상 URL이 아닌 동영상 원본을 받는 방법도 고려해본다.
(AWS S3 프리티어의 스토리지 용량은 5GB로 되어 있어서 URL을 입력받도록 했으나, 1분 미만의 동영상이기 때문에 Byte 코드로 쪼개면 서버 스토리지에 어찌저찌 저장할 것 같다는 생각이 들어서,,,,, 일단 고민해보기..!)

해당 기능을 구현하는 시점부터 Validation, Exception Handling를 꼼꼼하게 체크하고, 테스트(Test) 작성을 시작한다.
(++ Event Log도 어디에 꼽을지 고민해보기)

### 기타 논의 사항
- X

### 샘플
![image](https://user-images.githubusercontent.com/64416833/236636038-fee76bc0-83d1-4039-b03b-8f45f2a7aab5.png)

**Comment by ahn-sj** [comment]
#44 [FEAT] 좋아요, 북마크, 숏클래스 Entity를 추가한다.
#17 [FEAT] Creator, Tag, Follow Entity를 생성한다.

**Comment by ahn-sj** [comment]
별도 이슈로 분리시키는 것이 적절하다고 생각되어 이슈 닫습니다
