### ISSUE TITLE
[FEAT] 정기 회의에서 결정된 변경 사항들을 적용한다.

### ISSUE THREAD

**Issue by ahn-sj** [cround-team/cround-server#40]
## 기능 설명
- 사용자 회원가입 요청 정보 변경한다.
- 닉네임과 이메일은 서비스 내 유일하도록 설정한다.
- 크리에이터 태그는 최대 7개까지 생성 가능하고, 각 태그는 최대 20글자까지 가능하다.
- 프로필 이미지는 크리에이터만 존재한다.

## 기능 상세
- [x] 회원가입 요청 정보를 변경한다.
- [x] 회원가입시 이메일, 닉네임 중복 체크를 한다.
- [x] 크리에이터에 프로필 이미지(profile_image)를 추가한다.
- [x] 태그의 Validation을 추가한다.

## TODO
- [x] 회원가입할때 일반 사용자는 프로필 사진을 입력받지 않는다.
- [x] 회원가입할때 관심사(플랫폼, 테마)를 값 타입(@ElementCollection)으로 두어 별도의 테이블로 관리한다.
- [x] 서비스 내 유일성을 띄는 이메일, 닉네임에 대한 중복 검사 API를 추가한다.
- [x] 크리에이터만 프로필 이미지를 가지기 때문에 이미지 경로를 포함시킨다.
- [x] 크리에이터 태그는 최대 7개가 가능하고, 태그별 최대 20글자까지 가능하므로 Validation을 추가한다.
